# Generated by Django 2.2.7 on 2020-09-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200911_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10)),
                ('coupon_desc', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('issue_date', models.DateField()),
                ('expire_date', models.DateField()),
            ],
        ),
    ]
