# Generated by Django 2.2.7 on 2020-09-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
        migrations.AlterField(
            model_name='profile',
            name='coupons',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wishlist',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
